# Generated by Django 4.0.4 on 2022-10-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
